# Generated by Django 6.0.1 on 2026-01-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddytech', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='project',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(default='', help_text='e.g. Django, React, PostgreSQL', max_length=200),
            preserve_default=False,
        ),
    ]
